### PR TITLE
Bump stylelint to 11.x.x

### PR DESCRIPTION
**Pull request by Snack-X**
Stylelint has been updated to v11. This PR updates stylelint dependency.

Changelog: https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md

I'm submitting PR to this repository because this repository has been updated most recently among  other forks.

### CODE REVIEW

**Comment by axelboc** [comment]
Any chance this could be merged asap, please? 🙏

**Comment by wrobbler** [comment]
Stylelint has been updated to v12. There are some new rules in v11 that break the current version of the extension for ruleset, if those rules are applied in a project. Can somebody please update?

**Comment by JounQin** [comment]
For anyone maybe interested, you can try the following zipped package which includes all latest dependencies, and unzip it first after downloading, and then install it into VSCode manually. Good luck, cheers.

[stylelint-plus-0.52.3.vsix.zip](https://github.com/hex-ci/vscode-stylelint-plus/files/3963538/stylelint-plus-0.52.3.vsix.zip)

**Comment by GitGangGuy** [comment]
Coming from #8. I'd really appreciate not getting an error from stylelint-plus everytime I type something whilst only using the `stylelint-prettier/recommended` plugin. Thanks!

**Comment by Snack-X** [comment]
Found [new, updated, (probably) official extension](https://github.com/stylelint/vscode-stylelint) came out recently.

I think that would solve all the problems.

**Pull request closed without merging**
