### PR TITLE
fix #7 by adding "useLocal" option

### LINKED ISSUE #7: Use locally installed stylelint package
Is there any way the extension could use the local `stylelint` package from the currently open project? I believe other extensions work this way to simplify version management.

### LINKED ISSUE #8: "stylelint: Undefined rule unicode-bom"
I'm using this plugin having come from the shinnn version. My stylelint looks like:

```
{
  "extends": "stylelint-config-twbs-bootstrap/scss",
  "rules": {
    "selector-class-pattern": "^(?:(?:o|c|u|t|s|is|has|_|js|qa)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:\\[.+\\])?$",
    "declaration-no-important": null,
    "scss/dollar-variable-default": null,
    "color-hex-length": "long",
    "block-no-empty": null,
    "value-list-comma-newline-after": "always-multi-line",
    "value-list-comma-space-after": "always-single-line"
  }
}
```

and my `package.json`:

```
"stylelint": "^12.0.0",
"stylelint-config-twbs-bootstrap": "^0.9.0",
```

I'm getting the error:

> stylelint: Undefined rule unicode-bom

When I run stylelint. The issue (I assume) is that this extension is using its own internal version of stylelint that is < 12.0.0. 

Stylelint added support for this rule `unicode-bom` in version 12:

https://github.com/stylelint/stylelint/issues/4228
https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#1200

I can confirm that there is nothing wrong with my config or setup, as I'm able to run stylelint as a regular `gulp` task from my `node_modules` and it works perfectly. It seems the issue is that this extension is using its own version of stylling. 

Is it possible to use our own `node_modules` version of styleline?

### PR DESCRIPTION
**Pull request by konjac-potage**
also fixes #8, #11 and maybe #2

### CODE REVIEW

**Comment by JounQin** [comment]
Can we release a newer version?

**Comment by JounQin** [comment]
@konjac-potage I tried to pack it by myself, but it's not working.

**Comment by konjac-potage** [comment]
@JounQin Did you install stylelint locally in your project directory?

**Comment by JounQin** [comment]
@konjac-potage Yep, of course. But not directly, it's a dependence of my union [app-config](https://github.com/1stG/configs/blob/master/packages/app-config/package.json#L33).

**Comment by konjac-potage** [comment]
@JounQin The current strategy to find local 'stylelint' is:
1. find the root directory of the project by 'find-pkg-dir' from documentpath
2. load 'stylelint' form node_modules in the project root

That's why it cannot find your local 'stylelint'.


I think an option like 'stylelintPath' which defines the absolute or relative path to 'stylelint' package is better.
But in a multiple-root workspace, to resolve a relative path from ${workspaceRoot} is a little bit lazy for me.
So, I'm waiting for another Pull Request!

**Comment by JounQin** [comment]
> I think an option like 'stylelintPath' which defines the absolute or relative path to 'stylelint' package is better.

I don't think it is great for enforce end users to install global packages or config a relative path for every app.

**Comment by konjac-potage** [comment]
@JounQin 
By default, this extension uses the internal 'stylelint' package.
If users want to use the locally installed version, like ["typescript.tsdk"](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-the-workspace-version-of-typescript), set "stylelintPath" as
```
{
  "stylelintPath":  "node_modules/stylelint"
}
```
or set absolute path for globally installed version.
That was my idea.

**Pull request merged**
